server:
  port: ${AUTH_SERVICE_PORT:3001}
  servlet:
    context-path: /

spring:
  application:
    name: auth-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:roiplatform}
    username: ${DB_USER:roit}
    password: ${DB_PASSWORD:fhdlxpzm1*}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_POOL_MIN:2}
      maximum-pool-size: ${DB_POOL_MAX:10}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:10000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:2000}
      
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: ${LOG_SQL:false}
    show-sql: ${LOG_SQL:false}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: profile,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:roiplatform-jwt-secret-development-only}
  expiration: ${JWT_EXPIRES_IN:86400} # 24 hours in seconds
  refresh-expiration: ${JWT_REFRESH_EXPIRES_IN:604800} # 7 days in seconds

# Multi-tenant Configuration
tenant:
  header: ${TENANT_HEADER:X-Tenant-Id}
  default-locale: ${DEFAULT_LOCALE:ko}
  default-timezone: ${DEFAULT_TIMEZONE:Asia/Seoul}

# Logging Configuration
logging:
  level:
    com.roiplatform: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${LOG_SQL:false}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: false

    # Profile-specific overrides for Windows dev: disable Redis health if Redis isn't running
    ---
    spring:
      profiles: development
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      jpa:
        properties:
          hibernate:
            jdbc:
              batch_size: 25
              batch_versioned_data: true
            order_inserts: true
            order_updates: true
            generate_statistics: false
      datasource:
        hikari:
          leak-detection-threshold: 60000
          connection-test-query: SELECT 1
    management:
      health:
        redis:
          enabled: false
        db:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: when-authorized
          show-components: always
    ---
    spring:
      profiles: dev
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      jpa:
        properties:
          hibernate:
            jdbc:
              batch_size: 25
              batch_versioned_data: true
            order_inserts: true
            order_updates: true
            generate_statistics: false
      datasource:
        hikari:
          leak-detection-threshold: 60000
          connection-test-query: SELECT 1
    management:
      health:
        redis:
          enabled: false
        db:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: when-authorized
          show-components: always

# Application Information
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: ROIPLATFORM Authentication Service
